---
- name: Clone iotaas repo
  git:
    repo: git@github.com:danisafta/iotaas.git
    dest: /home/pi/code
    version: master
    accept_hostkey: yes
    key_file: /home/pi/.ssh/id_rsa

- name: Copy systemd service file to server
  copy:
    src: events.service
    dest: /etc/systemd/system
    owner: root
    group: root
  become: yes

- name: Start events service
  systemd:
    name: events
    state: started
    enabled: yes
  become: yes
