apiVersion: v1
kind: Service
metadata:
  name: collector-service-worker01
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5000

---
apiVersion: v1
kind: Endpoints
metadata:
  name: collector-service-worker01
subsets:
  - addresses:
      - ip: 192.168.100.52
    ports:
      - port: 5001