apiVersion: v1
kind: Service
metadata:
  name: collector-service-worker02
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5000

---
apiVersion: v1
kind: Endpoints
metadata:
  name: collector-service-worker02
subsets:
  - addresses:
      - ip: 192.168.100.37
    ports:
      - port: 5002