apiVersion: v1
kind: Service
metadata:
  name: collector-service-master
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: v1
kind: Endpoints
metadata:
  name: collector-service-master
subsets:
  - addresses:
      - ip: 192.168.100.50
    ports:
      - port: 5000