---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  {{ .Values.name }}-cronjob
spec:
  schedule: '@hourly'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.name }}
            image: "{{ .Values.images.cssrepository }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.images.pullPolicy }}
            env:
            - name: MASTER1
              value: 192.168.100.50
            - name: WORKER1
              value: 192.168.100.52
            - name: WORKER2
              value: 192.168.100.37
            envFrom:
            - secretRef:
                name:  {{ .Values.name }}-secret
          restartPolicy: OnFailure

