apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-exposer-deployment
  labels:
    app: {{ .Values.name }}-exposer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}-exposer
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-exposer
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.images.cserepository }}:{{ .Values.images.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        ports:
        - containerPort: 5000
        env:
          - name: MASTER1
            value: 192.168.100.50
          - name: WORKER1
            value: 192.168.100.52
          - name: WORKER2
            value: 192.168.100.37
        envFrom:
          - secretRef:
              name:  {{ .Values.name }}-secret
      nodeSelector:
        rpitype: fast 