apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
data:
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
  POSTGRES_PW: bDFjZW50YQ==
  POSTGRES_DB: cG9zdGdyZXNkYg==
  CLUSTER_TYPE: dGVzdC1jbHVzdGVyCg==
