---
- name: Clone iotaas repo
  git:
    repo: git@github.com:danisafta/iotaas.git
    dest: /home/pi/code
    version: master
    accept_hostkey: yes
    key_file: /home/pi/.ssh/id_rsa

- name: Create Python3.7 venv
  shell: python3.7 -m venv venv
  args:
    chdir: /home/pi/code/databank/collector/

- name: Install requirements
  shell: ./venv/bin/pip install -r requirements.txt
  args:
    chdir: /home/pi/code/databank/collector/

- name: Copy systemd service file to server
  copy:
    src: collector.service
    dest: /etc/systemd/system
    owner: root
    group: root
  become: yes

- name: Start collector service
  systemd:
    name: collector
    state: started
    enabled: yes
  become: yes

- name: Reboot
  shell: shutdown -r now