---
- name: Install Build tools and git
  become: yes
  apt:
    name: [ build-essential, git, libgpiod2]

- name: Install Python3.7 tools
  become: yes
  apt:
    name: [python3-dev, python3-venv, python3-openssl, python3-distutils, python3-apt, python3-pip, libssl-dev, libffi-dev, python3-setuptools ]

- name: Python get pip
  shell: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

- name: Install pip
  shell: python3.7 get-pip.py

- name: Install Adafruit libraries
  shell: /home/pi/.local/bin/pip3 install adafruit-circuitpython-dht

- name: Install aptitude package
  become: yes
  apt:
    name: aptitude
    force_apt_get: yes

- name: Upgrade all packages to the latest version
  become: yes
  force_apt_get: True
  apt:
    name: "*"
    state: latest
