# Generated by Django 3.2 on 2021-06-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='price',
            new_name='measurement',
        ),
    ]
