# Generated by Django 3.2 on 2021-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_rename_price_sensor_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='measurement',
        ),
        migrations.AddField(
            model_name='sensor',
            name='node',
            field=models.TextField(blank=True, null=True),
        ),
    ]
