---
- name: Install Build tools and git
  apt:
    name: [ build-essential, git, libgpiod2]

- name: Clone iotaas repo
  git:
    repo: git@github.com:danisafta/iotaas.git
    dest: /opt/iotaas
    version: master

- name: Install requirements
  shell: pip install -r requirements.txt
  args:
    chdir: /opt/iotaas/kubernetes-metrics/

- name: Create kube dir
  file: 
    path: /root/.kube
    owner: root 
    group: root 
    mode: 0755 
    state: directory

- name: Copy kubeconfig
  copy:
    src: kubeconfig
    dest: /root/.kube/config
    owner: root
    group: root

- name: Copy systemd service file to server
  copy:
    src: k8s-mon.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Start collector service
  systemd:
    name: k8s-mon
    state: started
    enabled: yes
